### ISSUE TITLE
咨询个控制台输出

### ISSUE THREAD

**Issue by kadingzz1** [hanwenlu2016/web-ui#11]
1、若直接运行debugrun   console的输出会有乱码  ctrl shlft F10 运行的
2、若python  run.py  运行   terminal输出 没有乱码 但是日志的格式也跟单独运行test_XXX的不一样
3、若直接运行方法，则日志格式输出正常

另外  yaml 编码格式都是 gbk的   如果编辑器 改成gkb的编码 那console输出都是乱码，智能是utf-8 然后把yaml单独reload成gkb  或者直接把yaml文件转成gkb编码的

**Comment by kadingzz1** [comment]
另外 auto 确实很好用  如果想auto不满足需求 想两个都用的话   是不是就得  用单个的对象 然后 相当于三个yaml都得用起来

**Comment by hanwenlu2016** [comment]
> 其他汽车确实很好用如果想自动不满足需要想两个都用的话是不是就得用个别的对象然后三个yaml都得用起来

auto 只需要一个yaml 依赖  用例和步骤 写在一起    非auto 需要依赖步骤yaml  和用例  yaml   两种模式理论上来说满足了。

**Comment by hanwenlu2016** [comment]
> 1、若直接运行debugrun控制台的输出乱码ctrl shlft F10运行的 日志2、若python run.py运行终端输出没有乱码但是的格式也跟着单独运行测试_XXX的不一样 3、若直接运行，则日志格式输出正常
> 
> yaml编码格式都是gbk的编辑器如果改成gkb的编码，那控制台输出都是乱码，智能是utf-8然后把yaml单独重载成gkb或者直接把yaml文件转成gkb编码的

关于乱码问题需要自己定位处理下 。因为我们使用的macos 可能在中文上有不兼容。

**Comment by hanwenlu2016** [comment]
> > 1、若直接运行debugrun日志的探测输出乱码控制软件F10运行的日志2、若python run.py运行终端输出没有乱码的格式也跟着单独运行测试_XXX则不一样 3、若直接运行，格式输出正常
> > yaml编码格式都是gbk的编辑器改成gkb的编码，那如果探测输出都是乱码，智能是utf-8然后把yaml单独重载成gkb直接或者把yaml文件转成gkb编码的
> 
> 关于乱码问题需要自己定位处理下。因为我们使用的macos 可能在中文上有不擅长的。

如果你解决了此问题也可以提交我合并

**Comment by kadingzz1** [comment]
乱码 没搞定  我现在不用console输出就不显示乱码了。但是也不显示loguru的自带的美化
如果是在函数里 直接右键运行函数测试类或方法   控制台输出有美化
如果是用pytest  运行，也有美化
如果是用python run.py去运行，则没有美化
