### ISSUE TITLE
切换iframe在自动化执行里面怎么添加

### ISSUE THREAD

**Issue by 19863333636** [hanwenlu2016/web-ui#12]
元素定位中经常遇到iframe，想把切iframe加入到web_exe中，大神啥时候更新考虑下~

**Comment by hanwenlu2016** [comment]
1web_base 里面包含了 switch_to_fram_el 函数是实现iframe。

**Comment by 19863333636** [comment]
切入切出iframe 自动执行的逻辑是怎么样的呀？我看它会走used_click的时候报错AttributeError: 'NoneType' object has no attribute 'click'

**Comment by hanwenlu2016** [comment]
> 切入切出iframe 自动执行的逻辑是怎么样的呀？我看它会走used_click的时候报错AttributeError: 'NoneType' object has no attribute 'click'

上个版本写错了。目前有很多都没支持yaml 自动操作。iframe切换已经增加 但是iframe切换 父节点 和默认节点都没有需要自己加。你们可以加了我合并
