### ISSUE TITLE
可以加一个请求的配置吗

### ISSUE THREAD

**Issue by hai588** [hanwenlu2016/web-ui#2]
老哥，看了你写的代码，很好，有时UI需要用到request请求，可以把加一个吗？自己基础薄弱，在慢慢摸索中

**Comment by hanwenlu2016** [comment]
> 老哥，看了你写的代码，很好，有时UI需要用到request请求，可以把加一个吗？自己基础薄弱，在慢慢摸索中

你的意思是封装一个基础request的操作还是？

**Comment by hai588** [comment]
是的，有时要用到接口的请求

发自我的 iPhone
