### ISSUE TITLE
USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)

### ISSUE THREAD

**Issue by zyaber-y** [hanwenlu2016/web-ui#21]
启动浏览器时，报错，浏览器一闪就关闭了
环境：
OS:  win10
chrome: 109.0.5414.120
chromedriver：109.0.5414.74

尝试更新驱动版本，修改配置chrome_options=options，未能解决此问题

**Comment by hanwenlu2016** [comment]
chromedriver版本不一致

**Comment by zyaber-y** [comment]
作者，能提供一个chrome及对应的chromedriver么，谢谢！

**Comment by zyaber-y** [comment]
上传文件功能，没看有呢

**Comment by zyaber-y** [comment]
能否提供一个上传文件的功能？

**Comment by zyaber-y** [comment]
能否提供一个上传文件的功能？
