### ISSUE TITLE
请教一下，第二个用例要在第一个用例后去执行，这个怎么处理

### ISSUE THREAD

**Issue by zyaber-y** [hanwenlu2016/web-ui#22]
比如：第一个用例执行，输入用户、密码 （每个步骤，测试数据，都是单独）
           第二个用例执行，需要在第一个用例的步骤后，再去执行
           driver需要怎么写，才能传递到下一个用例；

**Comment by hanwenlu2016** [comment]
@pytest.fixture() 在case里面加入对应的前置条件
