### ISSUE TITLE
django+rest_framework+react  请问这部分有时间开源么？

### ISSUE THREAD

**Issue by god-pane** [hanwenlu2016/web-ui#5]

**Comment by hanwenlu2016** [comment]
这部分目前只适合公司内部项目可用，公共的部分还在调整处理。

**Comment by hanwenlu2016** [comment]
> _没有提供说明。_

django+rest_framework 此部分目前只适合公司内部项目使用，公共部分还在梳理。

**Comment by god-pane** [comment]
后面会开源公共部分吗？，我对你们这个项目还挺感兴趣的。

**Comment by hanwenlu2016** [comment]
> 会成为这个公共部分吗？，我对你们项目还很漂亮的。

梳理完成会开源

**Comment by god-pane** [comment]
有大概的时间节点吗？

**Comment by hanwenlu2016** [comment]
> 有大概的时间节点吗？

有时间就梳理吧没有绝对的节点
