### ISSUE TITLE
我运行时候 提示GBK编码问题呢  小白求问

### ISSUE THREAD

**Issue by kadingzz1** [hanwenlu2016/web-ui#7]
我运行时候 提示GBK编码问题呢  小白求问

**Comment by hanwenlu2016** [comment]
具体的报错截图贴出来

**Comment by kadingzz1** [comment]
这个问题好了。pytest.ini 配置文件里包含中文注释。改了下源码的打开方式的编码格式搞定了  现在遇到一个新的问题
- casename: test_baidu_search     # 对应类的 函数
  title: 输入搜索内容            # 操作标题
  precond:        # 前置说明
  testdata:    # 测试数据 /列表
    - username: zhangzhen
      passwd: '123456'

yaml读取出的账号密码为元组格式。
web_base的webexe方法，判断的是获取数据是list
![image](https://user-images.githubusercontent.com/77272159/130001643-7e2597a4-a7d1-4f11-885a-097cc495b39e.png)

我测试的时候，导致用户名会同时输入账号+密码
我下面增加了个转换后才好了。
![image](https://user-images.githubusercontent.com/77272159/130002004-21d80789-bd43-4833-ad6b-dcc17c11452b.png)

是我测试用例输入的数据不对

**Comment by kadingzz1** [comment]
还有个问题想问下大佬 断言怎么用。看了会框架 没找到具体的断言的方法

**Comment by hanwenlu2016** [comment]
> 还有问题没问下大佬断言怎么用。
断言可以写在 testdata 数据里面 用系统自带短信去处理

**Comment by hanwenlu2016** [comment]
> 这个问题好了。pytest.ini 配置文件里有中文注释。改了下源码的打开方式的编码格式搞定了现在遇到一个新的问题
> ![图像](https://user-images.githubusercontent.com/77272159/130002068-0930208b-dd1d-4121-97c4-56d5a210c905.png)
> 
> yaml读取出的账号密码为元组格式。
> web_base的webexe方法，判断是获取数据是list
> ![图像](https://user-images.githubusercontent.com/77272159/130001643-7e2597a4-a7d1-4f11-885a-097cc495b39e.png)
> 
> 我测试的时候，导致用户名会同时输入
> 账号+密码我下面增加了个转换后才好。 是我测试用例输入的数据定位 框架还是这块的判断或者读取yaml方法需要改
> ![图像](https://user-images.githubusercontent.com/77272159/130004614-e9f674ef-7652-4742-a1ed-243075119523.png)
当ymal testdata只有一个参数时并有多个测试数据就会是列表  多个参数时就是元组

**Comment by kadingzz1** [comment]
当我有两个参数  每个参数有一个测试数据 
测试步骤 分两步的时候， 登录测试用例，最后执行结果是 用户名输入框会被输入用户名+密码

**Comment by hanwenlu2016** [comment]
> ![图像](https://user-images.githubusercontent.com/77272159/130017575-4f0bedb1-ee0e-4341-b544-0e8b681fd514.png)
> 
> 当我有两个参数参数参数有一个测试数据
> 测试步骤分两步的时候，登录测试用例，执行结果是用户名输入框会输入用户名+密码

记得当初是有这个问题后面有没有解决忘记了。有时间我看下或者你提交pull修复

**Comment by kadingzz1** [comment]
> > ![图像](https://user-images.githubusercontent.com/77272159/130017575-4f0bedb1-ee0e-4341-b544-0e8b681fd514.png)
> > 当我有两个参数参数参数有一个测试数据
> > 测试步骤分两步的时候，登录测试用例，执行结果是用户名输入框会输入用户名+密码
> 
> 记得当初是有这个问题后面有没有解决忘记了。有时间我看下或者你提交pull修复

我刚学这个 ，我不知道我自己临时改的有没有影响  我就是在webexe方法下增加了个这个
         if isinstance(text, tuple):
            text = list(text)
临时把读取的元祖转换成列表 暂时看起来是好的  没有动那个read yaml为元祖的方法 怕影响其他地方

**Comment by kadingzz1** [comment]
又看了会read_data 下此方法reda_web_casedata ，单参数返回的是列表   多参数时，返回的是列表，里面是元祖  
@pytest.mark.parametrize('content', reda_web_casedata(yamlfile, 'test_byhy_login'))  # 测试数据
经过pytest后   多参数时，content的值  是元祖 
在原来list的基础上  把元祖也加进去了 
![image](https://user-images.githubusercontent.com/77272159/130095221-73859c28-d2c1-4d64-a050-ca0f53583491.png)

**Comment by hanwenlu2016** [comment]
> 又此会读下read_data方法reda_web_casedata ，单参数返回列表多参数时，返回的是列表，里面是元祖
> @pytest.mark.parametrize('content', reda_web_casedata(yamlfile, 'test_byhy_login')) #测试数据
> 经过pytest后多参数时，内容的值是元祖
> 在原来的清单上的基础上把元也加进去了
> ![形象](https://user-images.githubusercontent.com/77272159/130095221-73859c28-d2c1-4d64-a050-ca0f53583491.png)
如果以页面对象模式编写不存在
![image](https://user-images.githubusercontent.com/38583116/130171017-dbb94ebe-ebae-4b4f-91c3-598564592092.png)

**Comment by kadingzz1** [comment]
多参数走元祖  就出现开始之前的那个问题  最后传参为[(admin, password)]  
content 就是(admin,password) 
走else
然后 用户名就给填入adminpassword了   而不是用户名密码 分别为admin  password

**Comment by kadingzz1** [comment]
还有个 此框架我不会用的地方
其他页面的测试的时候，我需要单独新建四个文件吗

两个yaml  两个py文件  然后里面 还需要重新写登录用例

**Comment by hanwenlu2016** [comment]
> 多参数走元祖 就出现开始之前的那个问题 最后传参为[(admin, password)]
> content 就是(admin,password)
> 走else
> 然后 用户名就给填入adminpassword了 而不是用户名密码 分别为admin password

嗯 但是你提交的代码不对，你可以自己改自己的逻辑。我可以在写一个只依赖yaml 来自动识别的函数

**Comment by hanwenlu2016** [comment]
> > 多参数走元祖就出现开始之前的那个问题最后传参为[(admin,password)]
> > 内容就是(admin,password)
> > 走else
> > 然后用户名就给填入adminpassword了不是用户而密码分别为admin密码
> 
> 嗯但是你提交的代码不对，你可以自己改自己的逻辑。我可以在写一个只依赖yaml来自动识别的函数

目前的建议是把所有操作封装为对象，比如输入 用户名就是一个对象一个函数  输入密码就是一个对象一个函数  。你现在的需求是想把整个逻辑写在一个对象里面所有有很多操作 这个要单一在写一个函数把这系列操作串联起来。

**Comment by hanwenlu2016** [comment]
> 还有个 此框架我不会用的地方
> 其他页面的测试的时候，我需要单独新建四个文件吗
> 
> 两个yaml 两个py文件 然后里面 还需要重新写登录用例

目前定位参数数据 和测试数据是需分离
页面操作和测试用列关联

**Comment by kadingzz1** [comment]
> > > 多参数走元祖就出现开始之前的那个问题最后传参为[(admin,password)]
> > > 内容就是(admin,password)
> > > 走else
> > > 然后用户名就给填入adminpassword了不是用户而密码分别为admin密码
> > 
> > 
> > 嗯但是你提交的代码不对，你可以自己改自己的逻辑。我可以在写一个只依赖yaml来自动识别的函数
> 
> 目前的建议是把所有操作封装为对象，比如输入 用户名就是一个对象一个函数 输入密码就是一个对象一个函数 。你现在的需求是想把整个逻辑写在一个对象里面所有有很多操作 这个要单一在写一个函数把这系列操作串联起来。

是的  我是这个想法  因为我觉得 部分测试用例 以组的形势，会比较维护 比如正确密码 错误密码这块
![image](https://user-images.githubusercontent.com/77272159/130198082-c0925b6b-1471-49ae-b973-28e05077a489.png)
